### ISSUE TITLE
Can't Upload Image for Face Detection

### ISSUE THREAD

**Issue by alphaolomi** [ojaswa1942/face-recognition-web-app#1]

**Comment by ojaswa1942** [comment]
sure..
an obvious thing to do is upload the image to the server and forward a public URL to Clarifai

**Comment by alphaolomi** [comment]
Sorry i mistakenly misspelled the issue 

i tried to upload an image but unfortunately i was facing issues.

**Comment by sheetalka** [comment]
Will this app make sure that the user has to provide the same image he once provided, to sign in every time ?
